# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aff3ct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aff3ct.proto',
  package='aff3ct',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61\x66\x66\x33\x63t.proto\x12\x06\x61\x66\x66\x33\x63t\"\xc2\x02\n\x07Message\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x0e.aff3ct.ResultH\x00\x12*\n\x0bpushRequest\x18\x02 \x01(\x0b\x32\x13.aff3ct.PushRequestH\x00\x12&\n\tpushReply\x18\x03 \x01(\x0b\x32\x11.aff3ct.PushReplyH\x00\x12*\n\x0bpullRequest\x18\x04 \x01(\x0b\x32\x13.aff3ct.PullRequestH\x00\x12&\n\tpullReply\x18\x05 \x01(\x0b\x32\x11.aff3ct.PullReplyH\x00\x12\x32\n\x0f\x64oEncodeRequest\x18\x06 \x01(\x0b\x32\x17.aff3ct.DoEncodeRequestH\x00\x12.\n\rdoEncodeReply\x18\x07 \x01(\x0b\x32\x15.aff3ct.DoEncodeReplyH\x00\x42\t\n\x07\x63ontent\">\n\x06Result\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.aff3ct.ResultType\x12\x12\n\nerror_text\x18\x02 \x01(\t\"2\n\x06Matrix\x12\t\n\x01n\x18\x01 \x01(\r\x12\t\n\x01m\x18\x02 \x01(\r\x12\x12\n\x06values\x18\x03 \x03(\x02\x42\x02\x10\x01\"7\n\x0bPushRequest\x12\x0b\n\x03var\x18\x01 \x01(\t\x12\x1b\n\x03mtx\x18\x02 \x01(\x0b\x32\x0e.aff3ct.Matrix\"+\n\tPushReply\x12\x1e\n\x06result\x18\x01 \x01(\x0b\x32\x0e.aff3ct.Result\"\x1a\n\x0bPullRequest\x12\x0b\n\x03var\x18\x01 \x01(\t\"H\n\tPullReply\x12\x1e\n\x06result\x18\x01 \x01(\x0b\x32\x0e.aff3ct.Result\x12\x1b\n\x03mtx\x18\x02 \x01(\x0b\x32\x0e.aff3ct.Matrix\"0\n\x0f\x44oEncodeRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\"G\n\rDoEncodeReply\x12\x1b\n\x03res\x18\x01 \x01(\x0b\x32\x0e.aff3ct.Result\x12\x19\n\x11\x63reated_resources\x18\x02 \x03(\t*%\n\nResultType\x12\x0b\n\x07Success\x10\x00\x12\n\n\x06\x46\x61iled\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RESULTTYPE = _descriptor.EnumDescriptor(
  name='ResultType',
  full_name='aff3ct.ResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Success', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=792,
  serialized_end=829,
)
_sym_db.RegisterEnumDescriptor(_RESULTTYPE)

ResultType = enum_type_wrapper.EnumTypeWrapper(_RESULTTYPE)
Success = 0
Failed = 1



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='aff3ct.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='aff3ct.Message.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pushRequest', full_name='aff3ct.Message.pushRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pushReply', full_name='aff3ct.Message.pushReply', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pullRequest', full_name='aff3ct.Message.pullRequest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pullReply', full_name='aff3ct.Message.pullReply', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doEncodeRequest', full_name='aff3ct.Message.doEncodeRequest', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doEncodeReply', full_name='aff3ct.Message.doEncodeReply', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='aff3ct.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=25,
  serialized_end=347,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='aff3ct.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='aff3ct.Result.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_text', full_name='aff3ct.Result.error_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=411,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='aff3ct.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='aff3ct.Matrix.n', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m', full_name='aff3ct.Matrix.m', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='aff3ct.Matrix.values', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=463,
)


_PUSHREQUEST = _descriptor.Descriptor(
  name='PushRequest',
  full_name='aff3ct.PushRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var', full_name='aff3ct.PushRequest.var', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtx', full_name='aff3ct.PushRequest.mtx', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=520,
)


_PUSHREPLY = _descriptor.Descriptor(
  name='PushReply',
  full_name='aff3ct.PushReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='aff3ct.PushReply.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=565,
)


_PULLREQUEST = _descriptor.Descriptor(
  name='PullRequest',
  full_name='aff3ct.PullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var', full_name='aff3ct.PullRequest.var', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=593,
)


_PULLREPLY = _descriptor.Descriptor(
  name='PullReply',
  full_name='aff3ct.PullReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='aff3ct.PullReply.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtx', full_name='aff3ct.PullReply.mtx', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=667,
)


_DOENCODEREQUEST = _descriptor.Descriptor(
  name='DoEncodeRequest',
  full_name='aff3ct.DoEncodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='aff3ct.DoEncodeRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='aff3ct.DoEncodeRequest.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=717,
)


_DOENCODEREPLY = _descriptor.Descriptor(
  name='DoEncodeReply',
  full_name='aff3ct.DoEncodeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='aff3ct.DoEncodeReply.res', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_resources', full_name='aff3ct.DoEncodeReply.created_resources', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=790,
)

_MESSAGE.fields_by_name['result'].message_type = _RESULT
_MESSAGE.fields_by_name['pushRequest'].message_type = _PUSHREQUEST
_MESSAGE.fields_by_name['pushReply'].message_type = _PUSHREPLY
_MESSAGE.fields_by_name['pullRequest'].message_type = _PULLREQUEST
_MESSAGE.fields_by_name['pullReply'].message_type = _PULLREPLY
_MESSAGE.fields_by_name['doEncodeRequest'].message_type = _DOENCODEREQUEST
_MESSAGE.fields_by_name['doEncodeReply'].message_type = _DOENCODEREPLY
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['result'])
_MESSAGE.fields_by_name['result'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['pushRequest'])
_MESSAGE.fields_by_name['pushRequest'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['pushReply'])
_MESSAGE.fields_by_name['pushReply'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['pullRequest'])
_MESSAGE.fields_by_name['pullRequest'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['pullReply'])
_MESSAGE.fields_by_name['pullReply'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['doEncodeRequest'])
_MESSAGE.fields_by_name['doEncodeRequest'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['doEncodeReply'])
_MESSAGE.fields_by_name['doEncodeReply'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_RESULT.fields_by_name['type'].enum_type = _RESULTTYPE
_PUSHREQUEST.fields_by_name['mtx'].message_type = _MATRIX
_PUSHREPLY.fields_by_name['result'].message_type = _RESULT
_PULLREPLY.fields_by_name['result'].message_type = _RESULT
_PULLREPLY.fields_by_name['mtx'].message_type = _MATRIX
_DOENCODEREPLY.fields_by_name['res'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['PushRequest'] = _PUSHREQUEST
DESCRIPTOR.message_types_by_name['PushReply'] = _PUSHREPLY
DESCRIPTOR.message_types_by_name['PullRequest'] = _PULLREQUEST
DESCRIPTOR.message_types_by_name['PullReply'] = _PULLREPLY
DESCRIPTOR.message_types_by_name['DoEncodeRequest'] = _DOENCODEREQUEST
DESCRIPTOR.message_types_by_name['DoEncodeReply'] = _DOENCODEREPLY
DESCRIPTOR.enum_types_by_name['ResultType'] = _RESULTTYPE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.Message)
  ))
_sym_db.RegisterMessage(Message)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.Result)
  ))
_sym_db.RegisterMessage(Result)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), dict(
  DESCRIPTOR = _MATRIX,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.Matrix)
  ))
_sym_db.RegisterMessage(Matrix)

PushRequest = _reflection.GeneratedProtocolMessageType('PushRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHREQUEST,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.PushRequest)
  ))
_sym_db.RegisterMessage(PushRequest)

PushReply = _reflection.GeneratedProtocolMessageType('PushReply', (_message.Message,), dict(
  DESCRIPTOR = _PUSHREPLY,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.PushReply)
  ))
_sym_db.RegisterMessage(PushReply)

PullRequest = _reflection.GeneratedProtocolMessageType('PullRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLREQUEST,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.PullRequest)
  ))
_sym_db.RegisterMessage(PullRequest)

PullReply = _reflection.GeneratedProtocolMessageType('PullReply', (_message.Message,), dict(
  DESCRIPTOR = _PULLREPLY,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.PullReply)
  ))
_sym_db.RegisterMessage(PullReply)

DoEncodeRequest = _reflection.GeneratedProtocolMessageType('DoEncodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOENCODEREQUEST,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.DoEncodeRequest)
  ))
_sym_db.RegisterMessage(DoEncodeRequest)

DoEncodeReply = _reflection.GeneratedProtocolMessageType('DoEncodeReply', (_message.Message,), dict(
  DESCRIPTOR = _DOENCODEREPLY,
  __module__ = 'aff3ct_pb2'
  # @@protoc_insertion_point(class_scope:aff3ct.DoEncodeReply)
  ))
_sym_db.RegisterMessage(DoEncodeReply)


_MATRIX.fields_by_name['values'].has_options = True
_MATRIX.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
