# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

class Action(object):
    Push = 0
    Pull = 1
    Exec = 2
    Encode = 3
    DecodeSIHO = 4
    DecodeSISO = 5
    DecodeHIHO = 6

